# Use an official Node runtime as a parent image
FROM node:14

# Set the working directory to /app/client
WORKDIR /app/client

# Copy the frontend files into the container at /app/client
COPY . .

# Install any needed packages specified in package.json
RUN npm install

# Define environment variable for the API URL
ENV REACT_APP_API_URL http://localhost:5000

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run npm start when the container launches
CMD ["npm", "start"]
