# Use an official Node runtime as a parent image
FROM node:14

# Set the working directory to /app
WORKDIR /app

# Copy the backend files into the container at /app
COPY . .

# Install any needed packages specified in package.json
RUN npm install

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variables
ENV DB_USER antov
ENV DB_PASS test1234
ENV DB_NAME multimedia_db
ENV DB_HOST 34.78.226.117
ENV INSTANCE_PORT 3306
ENV CORS_ORIGIN http://localhost:3000

# Run server.js when the container launches
CMD ["node", "server.js"]
