version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "5000:5000"
    environment:
      - DB_USER=antov
      - DB_PASS=test1234
      - DB_NAME=multimedia_db
      - DB_HOST=34.78.226.117
      - INSTANCE_PORT=3306

  frontend:
    build:
      context: client
      dockerfile: Dockerfile_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
